### ISSUE TITLE
Public secret

### ISSUE THREAD

**Issue by danieldmiller** [gl636474/google-photos-sync-mac#5]
https://github.com/gl636474/google-photos-sync-mac/blob/dc2be509b6a68ae5e8e1cd41113a070e526d8ffa/google_oauth_client.py#L5

Hello, thanks for the script! I noticed your client secret was listed publicly in the repo. You probably want to remove this from the repo. Consider something like Github secrets - https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

**Comment by gl636474** [comment]
Hi, thanks for saying thanks and for pointing that out. Stupidly I removed the credentials from one file and then re-committed them when adding the test scripts. You're welcome, hope it helps. Cheers, Gareth
